namespace: "ocp4"
name: "disconnected"
version: "0.1.1"
readme: "README.md"
authors:
    - "Matt Riensch (example@gmail.com)"
    - "Christopher Novak (example@gmail.com)"
dependencies:
    "dellemc.openmanage": "9.1.0"
    "containers.podman": "1.16.1"
    "ansible.posix": "1.5.4"
    "cisco.nxos": "8.1.0"
    "community.general": "9.4.0"
    "community.crypto": "2.22.0"
license:
    - "MIT"
repository: "https://github.com/cjnovak98/ocp4-disconnected-collection.git"
