{{- if ((.Values.cluster).ingress) }}

{{- with .Values.cluster.ingress }}

---

# Specifies a cert to use for ingress.
type: kubernetes.io/tls
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: openshift-ingress
apiVersion: v1
data:
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}

---

# Configures the ingress controller with the provided cert
# Cert specified in ingress-certs-secret.yaml
# Specifies a cert to use for ingress.
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: {{ .secretName }}

{{- end }}
{{- end }}