{{- if (.Values.storage) }}
{{- with .Values.storage }}
# Sets up a storage class to interact with a provisioner, marking it as default.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kuernetes.io/is-default-class: "true"
  name: basic-csi
parameters:
  backendType: ontap-nas
  fsType: nfs
provisioner: {{ .provisioner }}
volumeBindingMode: WaitForFirstConsumer
{{- end -}}
{{- end -}}