{{- if ((.Values.chrony).roles) }}
{{ range $i, $value := .Values.chrony.roles }}
# This sets the chrony configuraiton for specified node roles
# This is referenced in proxy.yaml
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ $value.role }}
  name: 99-{{ $value.role }}-chrony-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,{{ $.Values.chrony.configContent | b64enc }}
          filesystem: root
          mode: 420
          path: /etc/chrony.conf
# end chrony configs
{{ end }}
{{- end -}}