{{- with .Values.nncps.bond }}
{{- range $i, $curVlan := .vlans }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $.Values.nncps.bond.name }}-bridge-vlan{{ $curVlan.id }} 
  namespace: {{ $.Values.nadNamespace | default "default" }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "{{ $.Values.nncps.bond.name }}-bridge-vlan{{ $curVlan.id }}", 
    "type": "bridge", 
    "bridge": "br-{{ $.Values.nncps.bond.name}}.{{ $curVlan.id }}", 
    "macspoofchk": false, 
    "vlan": {{ $curVlan.id }}
  }'
{{- end -}}
{{- end -}}
