# Common
# debug: true
# argo_sync_ref: "58-add-structure-for-central-variable-management-for-end-to-end-worklow"
common_git_repos:
  - "https://github.com/ocp4-disconnected/collection.git"
  - "https://github.com/ocp4-disconnected/config.git"

#common_install_dir: "/home/your_user_dir" ## This can also be set to any root directory you'd like. It just needs permissions.
common_openshift_dir: /pods/content
common_connected_cluster: false
mirror_content_pull_mirror: false
media_share_webserver: true

#worker_iso_disk_type: sda
#agent_iso_cluster_name: ocp-sno
common_openshift_interface: enp1s0
#common_fips_enabled: false
common_cluster_domain: example.com

common_ip_space: 192.168.100
common_nodes:
  - name: master-0
    ip: '42'
    mac: 52:54:00:8d:13:77
  - name: worker-0
    ip: '43'
    mac: 52:54:00:8d:13:78

# Registry
#common_registry_volume: /pods/registry
#registry_username: openshift
#registry_password: CHANGEME


# iDRAC
#idrac: false
#idrac_user: test
#idrac_password: tester

media_share_idracs:
  - name: master-0
    ip: '{{ common_ip_space }}.5'
  - name: worker-0
    ip: '{{ common_ip_space }}.8'

# Single Node Worker

