# General cluster-level information
# cluster:
#   ca:
#    configMapName: cluster-proxy-ca
#    content: |- # The cluster's CA
#      ----- CA Content ------
#      ......
#      ----- end content ----
#  # Ingress related configuration.
#  ingress:
#    secretName: ingress-cert
#    cert: |- # The content of the ssl cert to use for ingress
#      ---- cert content ----
#      ....
#      ---- content ------
#    key: # The content of the ssl cert key to use for ingress
#      ----- cert content ----
#      .....
#      ----- cert content ----


# nncps:
#   bond:
#     name: bond0
#     bond:
#       ports:
#         - ens2f0
#         - ens2f1
#         - ens3f0
#         - ens3f1
#         # etc
#     vlans:
#       - id: 677
#       - id: 58
#       - id: 670
#       # etc
#   nodes:
#     - name: bond-ips
#       node: master-0
#       vlans:
#         - id: 672
#           ip: 192.168.1.1
#  - name: bond-ips-2
#    node: worker-0
#    vlans:
#      - id: 2 # TODO:: specify, int
#        ip: 192.168.1.2 # TODO:: specify
  # ... TODO:: fill out

# # LDAP configuration.
# ldap:
#  # The name of the LDAPSyncConfig (ldap-accounts.yaml)
#  syncConfigName: foo
#  accountName: sAMAccountName
#  bindDN: # like some.svc.ocp
#  bindPW: foo # plaintext password to access LDAP server
#  server:
#    name: # like NAME LDAP
#    urlFull: # like: ldap://fdqn/dn?accountName
#    urlShort: # like: ldap://fdqn
#  groupUIDNameMapping: '"cn=foo,ou=bar": foo' # Like "cn=foo,ou=bar...": bar
#  queries:
#    group:
#      baseDN: # Like "cn=foo,ou=bar..."
#    user:
#      baseDN: # Like "cn=foo,ou=bar..."
#      filter: # Like "(cn=foo,ou=bar...)"

# Chrony configuration.
# The chrony configuration defined in configContent is applied to all OCP nodes with each of the roles specified.
# chrony:
#   roles:
#     - role: master
#     - role: worker
#   configContent: |-
#     # EXAMPLE chrony config
#     server pool.ntp.org iburst
#     driftfile /var/lib/chrony/drift
#     makestep 10 3
#     rtcsync

# Storage settings for the cluster.
storage:
#   # The location of the trident/netapp host
  provisioner: csi.trident.netapp.io
  nad:
    mgmtAddress: "192.168.1.10/24"
    masterBond: "bond0.672"

