- name: Create {{ common_openshift_oc_mirror_dir }}
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ common_openshift_oc_mirror_dir }}"
  when: 
    - mirror_content_pull_mirror | bool
    - direction == 'pull'

- name: Include tasks to pull images
  include_tasks: pull_images.yml
  loop: 
    - cluster-images.yml
    - operators.yml
  loop_control:
    loop_var: item
  when: 
    - mirror_content_pull_mirror | bool
    - direction == 'pull'

- name: push images
  ansible.builtin.include_tasks: push_images.yml
  when: direction == 'push'