{{- range $i, $namespace := .Values.namespaces }}
---
# Defines the namespace we want to place the nmstate operator into
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ $namespace.ns }}
    name: {{ $namespace.ns }}
  name: {{ $namespace.ns }}
spec:
  finalizers:
  - kubernetes

{{- end }}
