{{- range $attr, $operator := .Values.operators }}
---
# Brings in the operator group used for the nmstate operator.
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    {{- if .providedAPIs }}
    olm.providedAPIs: {{ .providedAPIs }}
    {{- end }}
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  targetNamespaces:
  - {{ .namespace }}
{{- end }}