{{- range $attr, $operator := .Values.operators }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .subNamespace }}
spec:
  channel: {{ .channel | default "latest" }}
  installPlanApproval: {{ .installPlanApproval | default "Automatic" }}
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace | default "openshift-marketplace" }}
  {{- if eq .name "openshift-gitops-operator" }}
  config:
      env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: openshift-gitops, openshift-config
  {{- end }}
  {{- if .startingCSV }}
  startingCSV: {{ .startingCSV }}
  {{- end }}
{{- end }}
