{{- range $attr, $operator := .Values.operators }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  {{- if eq .name "openshift-mtv" }}
  labels:
    operators.coreos.com/mtv-operator.openshift-mtv: ""
  {{- end }}
  {{- if eq .name "openshift-nmstate" }}
  labels:
    operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
  {{- end }}
spec:
  channel: {{ .channel | default "latest" }}
  installPlanApproval: {{ .installPlanApproval | default "Automatic" }}
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace | default "openshift-marketplace" }}
  {{- if eq .name "openshift-gitops" }}
  config:
      env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: openshift-gitops, openshift-config
  {{- end }}
  {{- if .startingCSV }}
  startingCSV: {{ .startingCSV }}
  {{- end }}
{{- end }}
