---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-monitor-sa
  namespace: openshift-operators

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-monitor-role
  namespace: openshift-operators
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["*"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-monitor-rolebinding
  namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-monitor-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-monitor-sa
    namespace: openshift-operators
