{{- with .Values.compliance }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: compliance-operator-sub
  namespace: {{ .target_namespace | default "openshift-compliance" }}
spec:
  channel: {{ .channel | default "stable" }}
  installPlanApproval: Automatic
  name: compliance-operator
  source: {{ .catalog_source | default "cs-redhat-operator-index-v4-16" }}
  sourceNamespace: {{ .sourceNamespace | default "openshift-marketplace" }}

{{- end }}
