apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-day2
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - ansible_values.yaml
    path: ./helm/openshift-gitops-day2
    repoURL: git@192.168.4.57:repos/ocp4-disconnected-config
    targetRevision: 58-add-structure-for-central-variable-management-for-end-to-end-worklow
  syncPolicy:
    manual: {}
